In [ ]:
1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin
2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.
3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)
4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.
5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.
6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)
7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)
8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)
9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)
10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.
11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.
12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.
13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.
14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.
15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [3]:
import numpy as np

1 - Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin

In [ ]:
arr1 = np.array([[[1,2,3] , [4,5,6]] , [[7,8,9] , [10,11,12]]])
arr1.ndim

3

2 - 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

In [ ]:
arr2 = np.arange(34,115,6)
arr2

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

3 - 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)

In [4]:
arr3 = np.linspace(50,501,91)
arr3 = arr3.astype('int')
arr3.dtype

dtype('int64')

4 - 100(10 ** 2) ile 10000(10 ** 5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

In [5]:
arr4 = np.logspace(2,5,8)
arr4

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

5 - 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.

In [6]:
arr5 = np.array([[0,1,2] , [3,4,5] , [6,7,8]])
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6 - 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

In [9]:
arr6 = np.zeros((6,6) , dtype = int )
arr6

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

7 - 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)

In [14]:
arr7 = np.random.randint(0,100,(4,4))
arr7

array([[61, 92, 54,  4],
       [50, 84, 30, 43],
       [42, 50, 62, 40],
       [78, 71, 75, 18]])

8 - 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

In [20]:
arr8 = np.eye(8,8)
arr8 = arr8.astype('int')
arr8

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

9 - 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

In [21]:
arr9 = np.eye(5,5)
arr9 = arr9.astype('int')
arr9 * 3

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

10 - np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

In [24]:
arr10 = np.random.rand(6)
arr10

array([0.51258754, 0.61967555, 0.45023014, 0.81728343, 0.78231155,
       0.44382064])

11 - np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

In [29]:
arr11 = np.random.randint(50,101,(5,2))
arr11

array([[91, 97],
       [69, 77],
       [82, 88],
       [65, 96],
       [71, 63]])

In [28]:
arr11.dtype

dtype('int64')

12 - np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

In [30]:
arr12 = np.random.randint(100,1000,(2,5,5))
arr12

array([[[426, 106, 598, 930, 349],
        [894, 801, 740, 678, 915],
        [552, 543, 352, 680, 859],
        [393, 500, 288, 400, 893],
        [624, 418, 427, 233, 484]],

       [[724, 816, 285, 110, 897],
        [969, 646, 166, 946, 444],
        [828, 974, 435, 369, 680],
        [894, 751, 219, 590, 561],
        [712, 181, 842, 252, 184]]])

In [31]:
arr12.shape

(2, 5, 5)

In [32]:
arr12.ndim

3

13 - np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

In [35]:
arr13 = np.random.randint(0,101,10)
arr13

array([95, 90, 54, 89, 33, 30, 96,  5, 24, 59])

In [36]:
arr13.max()

96

In [37]:
arr13.min()

5

14 - np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

In [38]:
arr14 = np.random.randint(300,500,(2,2,5))
arr14

array([[[443, 339, 433, 337, 392],
        [386, 367, 449, 480, 450]],

       [[357, 317, 449, 367, 305],
        [388, 463, 403, 433, 459]]])

In [39]:
arr14.max()

480

In [45]:
arr14[0][1][3]

480

In [46]:
arr14.min()

305

In [47]:
arr14[1][0][4]

305

15 - 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [51]:
arr15 = np.arange(0,51)
arr15[19:35] = 500
arr15

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18, 500, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])